
#
server:
  port: 7777


spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/POFECT/pofect-config-repo
          search-paths: service-pofect, keycloak-pofect

encrypt:
  key-store:
    alias: selfsigned
    location: classpath:passkey.jks
    password: pofect1!
